### ISSUE TITLE
Neo4J

### ISSUE THREAD

**Issue by hanchingyong** [jianyangg/local-llm#9]
Explore other features of Neo4J: Focus on exploring DAGs to link data 

- [x] HC: to provide more data that is relevant
- [x] HC: to find out if enterprise Neo4J can be shared with JY, and to check on capabilities of our enterprise Neo4J
- [x] Authentication with Neo4J -> using nodelabels for now

If you are interested and have time, can explore and help do a "lit-review" on Isolated Databases in Neo4J?
- I'm curious about how it works? Is there a centralised DB that we maintain? or is really spinning up isolated databases? If centralised, can it be "prompt-hacked"? And what is the difference between Isolated Databases and your method of tagging metadata?

**Comment by jianyangg** [comment]
Internal note: Current implementation simply tags each index to the tenant-id (a hashed identifier for the tenant). It cannot be prompt-hacked since the llm doesn't determine which tenant's database to fetch data from. This logic is handled in the backend by the orchestrator. The community edition of Neo4j unfortunately limits users to only 1 database.
